
services:
  astro-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    command: npx astro dev --host